### ISSUE TITLE
Character sets are another kind of useful pivots

### ISSUE THREAD

**Issue by yodantauber** [coapp/coapp.powershell#25]
Many C++ libraries have separate project configurations for ANSI/Unicode/Multibyte character sets. I think it would be useful to be able to create conditions based on the project character set out-of-the-box.

If I understand correctly, the _UNICODE and _MBCS defines are to be used to detect the character set.

**Comment by fearthecowboy** [comment]
I'm adding a CharacterSet pivot to the default template:

``` css
    CharacterSet { 
        key : "CharacterSet"; 
        choices: {  MultiByte, Unicode };
    };
```

with that, you can use `Multibyte` and `Unicode` in a pivot.

G
