### ISSUE TITLE
Specify deep directory structure for "content" files in C++ nuget pacakges

### ISSUE THREAD

**Issue by gordonwatts** [coapp/coapp.powershell#27]
I have a C++ library that requires a specific directory structure for data files. The root of these files should be the same location as the executable. Current the tool seems to only allow top level files, though it will maintain a deep directory structure in the nuget package itself.

Below is a autopkg file, which specifies files in the "etc" directory. I would like them, after build, to appear in an etc folder that sits next to the .exe (or whatever) is built. Currently all files, no matter how deep inside the etc directory, appear at the top level, right next to the build project executable.

Somehow I need an argument to CopyToOutput that will keep the folder structure...

```
    nuget {
        nuspec {
            id = ROOT;
            version = 5.34.09.0018;
            title = ROOT;
            authors = {CERN};
            owners = {G. Watts};
            licenseUrl: "http://root.cern.ch/drupal/content/license";
            projectUrl: "http://root.cern.ch";
            iconUrl: "http://root.cern.ch/drupal/sites/default/files/rootdrawing-logo.png";
            requireLicenseAcceptance: false;
            summary: The complete ROOT data analysis toolkit for C++;
            description: Contains all libraries needed for the full set of ROOT utilities;
            releaseNotes: "Release v5.34.09 of ROOT";
            tags: data;
        };

        files {
            etc += {
                #output {
                    package = redist;
                };
                #add-each-file : ::nuget.[redist]targets.[${condition}].CopyToOutput;
                #destination : ${d_bin}\etc;
            };

            include: { "root\include\*"};
            [x86,dynamic] {
                lib: { "root\lib\*.lib" };
                bin: { "root\bin\*.dll" };
                etc: { "root\etc\**\*" };
            };
                    }

        props {
            //@alias ForcedIncludeFiles = ItemDefinitionGroup.ClCompile.ForcedIncludeFiles;
            ItemDefinitionGroup.ClCompile.ForcedIncludeFiles += "w32pragma.h";
            //ForcedIncludeFiles += "w32pragma.h";
        }

        targets {
            Defines += "_LATER";
        }
    }

```

**Comment by fearthecowboy** [comment]
Hmm. Good idea.

CopyToOutput really _should_ take into account the relative directory.

Is it ok if we make this work slightly differently? Perhaps by asking it to copy the folder across (something like this:)

``` css
  // ... 
  files {
            etc += {
                #output {
                    package = redist;
                };
                // use add-folder instead?
                #add-folder : ::nuget.[redist]targets.[${condition}].CopyToOutput;
                #destination : ${d_bin}\etc;
            };

    // ...
```

That would be much more efficient.  (since we'd only need the one task for the whole tree copy)

This might work right now, but I suspect that I might have to create an `ItemGroup` that explicitly declares the `<sourcedir>\**` because MSBuild's Copy Task doesn't take directories for `SourcFiles` directly.

**Comment by gordonwatts** [comment]
That would work just fine. And I think that syntax makes it more clear what the intent is, so it is better than trying to modify the CopyToOutput in the add-each-file. I think it covers all the possible use cases I can think of:
- Put a single file in the root output directory. Works as it does now.
- Copy a folder into the output root directory. Use #add-folder, have the #destination be the same location as where you want it in the final build.
  - Put a single file somewhere deep in the output directory structure. Specify the directory structure in the definition of etc above, then add the files as above. Only means you can't re-direct files on a case by case basis, you'll have to define an "etc" like structure for each output directory destination.
  - Copy a folder somewhere deep in the output directory structure. Symmetric to above.
  
  The only weird thing is that we are specifying a directory to be copied over in the "files" syntax. However, given the way you have already designed it, I don't suppose that is too confusing. Heck, I was able to figure it out without too much documentation.
  
  Should "#add-folder" be "#add-destination-folder" or similar? To make it clear what folder was being added? It wasn't the folders that were being specified in the "etc: {...}", but, rather, the destination folder that we being added all at once.

And yes, I think you might have to do something with an ItemGroup. I was looking up the copy task and trying to see if it would take a folder so I could see if I could fake-it-out.

**Comment by yodantauber** [comment]
I also vote for this. Note that it is highly related to my issue #20 (including the comments I added later). The most important idea mentioned there and not here is that the destination folders (DLL folder, data folder) should be configurable by the consumer.

**Comment by gordonwatts** [comment]
I would second yodantauber's comment above!

**Comment by fearthecowboy** [comment]
You both have been extremely valuable in helping make this stuff a lot more solid.

**Comment by gordonwatts** [comment]
And I think I speak for both of us in saying thank you for doing all this work!

**Comment by fearthecowboy** [comment]
Thanks :D

My one regret with this stuff, is that my great idea for how to do a high-performance, arbitrary, programatic data binding between the model that I read the property sheets into and anything else (the MSBuild model in this case) turned out to be way too complex, and nearly impossible for anyone to trace what I'm doing. 

Some time over the next year, I'm going to try and remove that code and just pull the data out a bit more manually, so that someone can eventually understand how to add things to the tool.

I've wondered if I could use something like the data binding stuff in RxUI, but I get the feeling that it's not quite what I'm looking for.

**Comment by gordonwatts** [comment]
I have to admit that I thought it was very cool I could just add a new property in there and it just worked (the forced includes - though see my bug report on the infinite recursion it can cause if not done "right"). I hope you'll keep features like that. There are so many properties in the VC model that I would think it would be painful to do everything totally manually. So, keep some of the features - they have very nice use cases!

**Comment by fearthecowboy** [comment]
Yeah, that was kinda the whole motivation behind the grand scheme. I needed to make sure that anything you could do in a VCXProj file, you could do **templated** 

I really couldn't think of another way (and really, still _haven't_) but rest assured that's all stayin'

**Comment by gordonwatts** [comment]
Ok, the only other thing I can think of that you could do is actually use the MSBuild files, but add an extra templating language over them. On the other hand, the very nice concise syntax is great for people like me. Perhaps if you had to start again from scratch you could do the 80-20 rule? Make 80% of the cases trivial, and then for the last 20% basically give access to the actual MSBuild syntax somehow (so you won't loose all 80%). At any rate, what you have now is pretty nice. As always, just one more feature! ;-)

**Comment by fearthecowboy** [comment]
LOL.

I actually tried to use msbuild directly, it wasn't going to work out (for so very many reasons) -- there was just no simple way to express the vast amount of flexibility that I needed.

Believe it or not, what you see now is in effect the **fourth** rewrite; 

Still, from 90% of user's perspective, I can't imagine this being any simpler than I've made it.

**Comment by gordonwatts** [comment]
No, I agree. It is dirt simple right now. And the things we are asking are add-ons - like better wildcard parsing, or the directory structure - these don’t really affect your basic design decision.

Cheers,
    Gordon.

From: Garrett Serack
Sent: ‎Thursday‎, ‎October‎ ‎3‎, ‎2013 ‎1‎:‎27‎ ‎PM
To: coapp/coapp.powershell
Cc: Gordon Watts

LOL.

I actually tried to use msbuild directly, it wasn't going to work out (for so very many reasons) -- there was just no simple way to express the vast amount of flexibility that I needed.

Believe it or not, what you see now is in effect the fourth rewrite; 

Still, from 90% of user's perspective, I can't imagine this being any simpler than I've made it.

**Comment by fearthecowboy** [comment]
Wuff; I'm nearly there. Had to track down a really _really_ **really** obscure bug in my data mapping code. 

Regardless, I've got it pretty much working, I still gotta remove the old CopyToOutput code, and fix up the templates so that existing .autopkg files work like they currently do...

What I've done is allowed you to create pivot/combination supported  `<ItemGroup>` s in the generated project files.

With that you can easily add a task that manipulates the contents of the `<ItemGroup>` 

I've still got a bit of tweaking to do, but it should come out something like this:

``` css

files {
    etc += {
        /*  destination in the *package* */
        #destination : ${d_bin}/etc;  

        /* #add-all-files adds this destination folder + "/**" (to recurse for all files)
           to the specified node */
        #add-all-files : { ::nuget.targets.[${condition}].ItemGroup.MyEtcFiles };

        /* #add-folder adds just the destination folder to the target node
           #add-folder : { ::nuget.targets.[${condition}].ItemGroup.MyEtcFiles }; */

        /* #add-each-file adds each individual file to the target node 
           (if you were doing a file copy, this would have the effect of flattening the tree)
           #add-each-file : { ::nuget.targets.[${condition}].ItemGroup.MyEtcFiles }; */
    };

    [x64] 
    etc : {
        x64\foo.dll, x64\bar.dll
    };

    [x86] 
    etc : {
        win32\foo.dll, win32\bar.dll
    };


};

// ...

targets {

    /* nodes that are unrecognized and don't look like simple properties
     are treated as <Target> nodes  */
    AfterBuild {
        /* Some <Target> nodes are handled specially (things like 
           "AfterBuild", "BeforeBuild", "BeforeLink","Build","Rebuild", etc )
           In these cases the tool generates a project-specific 
           version, and chains it to run after the Top-Level Target
           ie: in zlib, AfterBuild becomes zlib_AfterBuild and chains it 
           to the Top-Level AfterBuild. */

        /* Tasks can be emitted in a target by preceeding them with
           a dot (otherwise, their definitions would merge/overwrite) */
        .Copy {
            /* then the attributes of the <Task> are just
               properties in the .<Task> node */
            DestinationFolder = "$(TargetDir)etc";

            /* in this case, we get the sum of all the MyEtcFiles 
               that are placed in the outputs 
               and it only picks up the ones that are 
               matching the right pivot combination. */
            SourceFiles = "@(MyEtcFiles)";
        };

    };
}

```

I will probably put in a couple of `@alias` declarations that will make a bit of that simpler for the low-hanging fruit.

perhaps something like:

``` css



/* so that you can do stuff like this: */
files {
    @alias Items  ::nuget.targets.[${condition}].ItemGroup;

    etc += {
        #destination : ${d_bin}/etc;  

        #add-all-files : { Items.MyEtcFiles };
    };


```
